# Generated by Django 4.1.5 on 2023-02-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0002_trackm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artist_id', models.CharField(max_length=250)),
            ],
        ),
    ]
