# Generated by Django 4.1.5 on 2023-02-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_id',
            field=models.CharField(max_length=150),
        ),
    ]
