# Generated by Django 4.1.5 on 2023-02-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0007_alter_artist_artist_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artist_id', models.CharField(max_length=150)),
            ],
        ),
    ]
