# Generated by Django 4.1.5 on 2023-02-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0008_artistm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtistM',
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='artist',
            name='spotify_url',
            field=models.CharField(default='', max_length=150),
        ),
    ]
