# Generated by Django 4.1.5 on 2023-02-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0009_delete_artistm_artist_genres_artist_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_id',
            field=models.CharField(max_length=100),
        ),
    ]
