# Generated by Django 4.1.5 on 2023-02-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0010_alter_artist_artist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
