# Generated by Django 4.1.5 on 2023-02-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0011_alter_artist_artist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='id',
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
