# Generated by Django 4.1.5 on 2023-02-18 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0012_remove_artist_id_alter_artist_artist_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrackM',
            new_name='Track',
        ),
        migrations.DeleteModel(
            name='SpotifyToken',
        ),
    ]
